name: Build

on: workflow_dispatch

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
  build-libs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4.0.1

    - name: Initialise git
      run: |
        git pull

    - name: Build
      run: bash build.sh

    - name: Push build
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Build output" -a
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-demos:
    needs: build-libs

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 1

      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        # AOT only seems to support 64 bit archs
        # ubuntu-latest, arm64 is not supported...
        arch: [x32, x64, arm, arm64]
        #exclude:
          #- os: ubuntu-latest
            #arch: arm64

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.0.1

      - name: Initialise git
        run: |
          git pull

      - name: Build
        run: |
          cd demo
          bash build.sh
        env:
          ARCH: ${{ matrix.arch }}

      - name: Push build
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          git commit -m "Build output" -a
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
